### ISSUE TITLE
Site says all ROM files are invalid

### ISSUE THREAD

**Issue by HunterAhlquist** [kchapelier/procjam2020-smb3#1]
I've tried different revisions, and the site says they're all invalid. 
I'm using the US copy, should it be a different region?

**Comment by kchapelier** [comment]
Hello, that's annoying. It should work with .nes ROM (iNES format if I'm not mistaken) of the European version and of the first US version (Prg0 / Revision 0). I'm not sure about the original japanese version or the second US version (Prg1 / Revision 1). I think they worked using the Uprg0 codepath, but not 100% sure.

Do you know the specifics of the files you tried ? Could you send them to me ( kevin.chapelier+procjam@gmail.com ) ?

**Comment by kchapelier** [comment]
Was able to confirm all the rom versions discussed are accepted and modified correctly.
